### ISSUE TITLE
Actividad 11_Unidad 4

### ISSUE THREAD

**Issue by A-Lorely-Z** [SistemasTecTlaxiaco/compuertas-logicas-lennin-s-team-1as#1]
[Actividad 11.Unidad 4.pdf](https://github.com/user-attachments/files/18049897/Actividad.11.Unidad.4.pdf)

**Comment by AlynGomez12** [comment]
Portada:25/25
Procedimiento/Desarrollo:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
